#' Run FlyPhone pipeline
#'
#' Wrapper function for the FlyPhone pipeline.
#'
#' @param knowledgebase_version Version of knowledgebase to use. Valid values are: "Version 1", "Version 2 All", "Version 2 High", and "Version 2 High/Moderate".
#' @param counts_fn The filepath to the counts matrix.
#' @param metadata_fn The filepath to the accompanying metadata file.
#' @param delimitor The separator for the counts file if it is a .txt file. Default is tab.
#' @param seuratObject Optionally can upload a Seurat Object instead of a matrix/metadata file pair.
#' @param DEG The filepath to the DEG file, if provided.
#' @param control_name The name of the control sample, if applicable.
#' @param mutant_name The name of the mutant sample, if applicable.
#' @param pct_filter Percent threshold to filter expression of genes by. Default value of 0.1.
#' @param perm_times The number of times to shuffle cluster alignments and calculate ligand/receptor averages for p-value calculation in raw interaction scoring. Default value of 1000.
#' @param deletePE Whether or not to delete the percentage expression file after the pipeline is finished. Defaults to true.
#' @param base_output_dir The directory for FlyPhone to send all result files to. Defaults to the current working directory.
#'
#' @return NULL
#'
#' @export
RunFlyPhone <- function(knowledgebase_version, counts_fn = NULL, metadata_fn = NULL, delimitor = "\t", seuratObject = NULL, DEG = NULL, control_name = NULL, mutant_name = NULL, pct_filter = 0.1, perm_times = 1000, deletePE = TRUE, base_output_dir = "") {
  # Preprocessing --------------------------------------------------------------

  # Boolean for checking if a DEG file is provided
  DEG_exists <- !is.null(DEG) && file.exists(DEG)

  # Load in annotation and pathway core component data depending on the knowledgebase version chosen
  annotationObj <- getAnnotationFile(knowledgebase_version)
  pathwayObj <- getPathwayFile(knowledgebase_version)

  # Initial subfolder creation
  dir.create(paste0(base_output_dir, "output"))
  dir.create(paste0(base_output_dir, ".temp"))

  # Pipeline -------------------------------------------------------------------

  # Calculate the raw interaction scores
  results <- CalculateInteractions(counts_fn, metadata_fn, annotationObj, pathwayObj, perm_times, knowledgebase_version, delimitor, seuratObject, base_output_dir)

  # Read in sample names generated by CalculateInteractions()
  sampleNames <- gsub('^"|"$', '', readLines(paste0(base_output_dir, "sample_names.txt")))

  # Boolean for if multiple samples were detected
  isMultiSample <- length(results) > 1

  # Create the rest of the subfolders
  if(isMultiSample & DEG_exists) {
    dir.create(paste0(base_output_dir, "output/comparison"))
    dir.create(paste0(base_output_dir, "output/comparison/heatmaps"))
    dir.create(paste0(base_output_dir, "output/comparison/chord-diagrams"))
    dir.create(paste0(base_output_dir, "output/comparison/circleplots"))

    for(name in sampleNames) {
      dir.create(paste0(base_output_dir, "output/", name, "/pathway-visualizations"))
      dir.create(paste0(base_output_dir, "output/", name, "/heatmaps"))
      dir.create(paste0(base_output_dir, "output/", name, "/dotplots"))
      dir.create(paste0(base_output_dir, "output/", name, "/chord-diagrams"))
      dir.create(paste0(base_output_dir, "output/", name, "/circleplots"))
      dir.create(paste0(base_output_dir, "output/", name, "/pathway-visualizations"))
    }

  } else {
    for(name in sampleNames) {
      dir.create(paste0(base_output_dir, "output/", name, "/heatmaps"))
      dir.create(paste0(base_output_dir, "output/", name, "/dotplots"))
      dir.create(paste0(base_output_dir, "output/", name, "/chord-diagrams"))
      dir.create(paste0(base_output_dir, "output/", name, "/circleplots"))
      dir.create(paste0(base_output_dir, "output/", name, "/pathway-visualizations"))
    }
  }

  # Only perform multi-sample analysis if a DEG file is provided
  if(isMultiSample & DEG_exists) {
    AnalyzeSingle(results, pct_filter, knowledgebase_version, base_output_dir)
    AnalyzeMultiple(results, DEG, pct_filter, control_name, mutant_name, base_output_dir) #FIXME: Might not actually use this variable at all
  } else {
    # Single-sample analysis OR Multi-sample analysis WITHOUT a DEG file provided
    AnalyzeSingle(results, pct_filter, knowledgebase_version, base_output_dir)
  }

  doMultivis <- isMultiSample && DEG_exists

  # Generate cell-cell communication visualizations
  GenerateVisualizations(counts_fn, metadata_fn, DEG, doMultivis, pathwayObj, delimitor, seuratObject, base_output_dir)

  # Generate pathway summary visualizations
  print("Generating pathway visualizations...")
  PathwayELVisualizations(base_output_dir)

  # Remove the percentage expression file from the final output
  if(deletePE) {
    print("Deleting Percentage_Expression.csv...")
    file.remove(paste0(base_output_dir, ".temp/Percentage_Expression.csv"))
  }

  print("Generating output_type.txt...")
  outputType_filepath <- paste0(base_output_dir, "output_type.txt")

  # Create a textfile specifying the type of analysis done
  if(isMultiSample & DEG_exists) {
    write.table("Multi_DEG", outputType_filepath, row.names = FALSE, col.names = FALSE)
  } else if (isMultiSample & !DEG_exists) {
    write.table("Multi", outputType_filepath, row.names = FALSE, col.names = FALSE)
  } else {
    write.table("Single", outputType_filepath, row.names = FALSE, col.names = FALSE)
  }
}

# If you only want to generate the data, not the visualizations ----------------

#' Single Analysis
#'
#' Generate single sample analysis data for any given amount of samples.
#'
#' @param knowledgebase_version Version of knowledgebase to use. Valid values are: "Version 1", "Version 2 All", "Version 2 High", and "Version 2 High/Moderate".
#' @param counts_fn The filepath to the counts matrix.
#' @param metadata_fn The filepath to the accompanying metadata file.
#' @param delimitor The separator for the counts file if it is a .txt file. Default is tab.
#' @param seuratObject Optionally can upload a Seurat Object instead of a matrix/metadata file pair.
#' @param pct_filter Percent threshold to filter expression of genes by. Default value of 0.1.
#' @param perm_times The number of times to shuffle cluster alignments and calculate ligand/receptor averages for p-value calculation in raw interaction scoring. Default value of 1000.
#' @param deletePE Whether or not to delete the percentage expression file after the pipeline is finished. Defaults to true.
#' @param base_output_dir The directory for FlyPhone to send all result files to. Defaults to the current working directory.
#'
#' @return NULL
#'
#' @export
RunSingleAnalysis <- function(knowledgebase_version, counts_fn = NULL, metadata_fn = NULL, delimitor = "\t", seuratObject = NULL, pct_filter = 0.1, perm_times = 1000, deletePE = TRUE, base_output_dir = "") {
  # Load in annotation and pathway core component data depending on the knowledgebase version chosen
  annotationObj <- getAnnotationFile(knowledgebase_version)
  pathwayObj <- getPathwayFile(knowledgebase_version)

  # Initial subfolder creation
  dir.create(paste0(base_output_dir, "output"))
  dir.create(paste0(base_output_dir, ".temp"))

  # Pipeline -------------------------------------------------------------------

  # Calculate the raw interaction scores
  results <- CalculateInteractions(counts_fn, metadata_fn, annotationObj, pathwayObj, perm_times, knowledgebase_version, delimitor, seuratObject, base_output_dir)

  # Read in sample names generated by CalculateInteractions()
  sampleNames <- gsub('^"|"$', '', readLines(paste0(base_output_dir, "sample_names.txt")))

  # Boolean for if multiple samples were detected
  isMultiSample <- length(results) > 1

  # Perform Single Sample Analysis
  AnalyzeSingle(results, pct_filter, knowledgebase_version, base_output_dir)

  # Remove the percentage expression file from the final output
  if(deletePE) {
    print("Deleting Percentage_Expression.csv...")
    file.remove(paste0(base_output_dir, ".temp/Percentage_Expression.csv"))
  }
}

#' Multi Analysis
#'
#' Generate multi sample analysis data.
#'
#' @param knowledgebase_version Version of knowledgebase to use. Valid values are: "Version 1", "Version 2 All", "Version 2 High", and "Version 2 High/Moderate".
#' @param counts_fn The filepath to the counts matrix.
#' @param metadata_fn The filepath to the accompanying metadata file.
#' @param delimitor The separator for the counts file if it is a .txt file. Default is tab.
#' @param seuratObject Optionally can upload a Seurat Object instead of a matrix/metadata file pair.
#' @param DEG The filepath to the DEG file, if provided.
#' @param control_name The name of the control sample, if applicable.
#' @param mutant_name The name of the mutant sample, if applicable.
#' @param pct_filter Percent threshold to filter expression of genes by. Default value of 0.1.
#' @param perm_times The number of times to shuffle cluster alignments and calculate ligand/receptor averages for p-value calculation in raw interaction scoring. Default value of 1000.
#' @param deletePE Whether or not to delete the percentage expression file after the pipeline is finished. Defaults to true.
#' @param base_output_dir The directory for FlyPhone to send all result files to. Defaults to the current working directory.
#'
#' @return NULL
#'
#' @export
RunMultiAnalysis <- function(knowledgebase_version, counts_fn = NULL, metadata_fn = NULL, delimitor = "\t", seuratObject = NULL, DEG = NULL, control_name = NULL, mutant_name = NULL, pct_filter = 0.1, perm_times = 1000, deletePE = TRUE, base_output_dir = "") {
  # Preprocessing --------------------------------------------------------------

  # Boolean for checking if a DEG file is provided
  DEG_exists <- !is.null(DEG) && file.exists(DEG)

  if(!DEG_exists) {
    stop("Error: RunMultiAnalysis() requires a DEG file!")
  }

  # Load in annotation and pathway core component data depending on the knowledgebase version chosen
  annotationObj <- getAnnotationFile(knowledgebase_version)
  pathwayObj <- getPathwayFile(knowledgebase_version)

  # Initial subfolder creation
  dir.create(paste0(base_output_dir, "output"))
  dir.create(paste0(base_output_dir, ".temp"))

  # Pipeline -------------------------------------------------------------------

  # Calculate the raw interaction scores
  results <- CalculateInteractions(counts_fn, metadata_fn, annotationObj, pathwayObj, perm_times, knowledgebase_version, delimitor, seuratObject, base_output_dir)

  # Read in sample names generated by CalculateInteractions()
  sampleNames <- gsub('^"|"$', '', readLines(paste0(base_output_dir, "sample_names.txt")))

  # Boolean for if multiple samples were detected
  isMultiSample <- length(results) > 1

  dir.create(paste0(base_output_dir, "output/comparison"))

  # Perform Multi Sample Analysis
  AnalyzeMultiple(results, DEG, pct_filter, control_name, mutant_name, base_output_dir)

  # Remove the percentage expression file from the final output
  if(deletePE) {
    print("Deleting Percentage_Expression.csv...")
    file.remove(paste0(base_output_dir, ".temp/Percentage_Expression.csv"))
  }
}

# Helper Functions -------------------------------------------------------------

# Gets the appropriate ligand/receptor pair dataset based on the knowledgebase version chosen
getAnnotationFile <- function(knowledgebase_version) {
  if(identical(knowledgebase_version, "Version 1")) {
    return(FlyPhone:::V1)
  } else if(identical(knowledgebase_version, "Version 2 High")) {
    return(FlyPhone:::V2H)
  } else if(identical(knowledgebase_version, "Version 2 High/Moderate")) {
    return(FlyPhone:::V2HM)
  } else if(identical(knowledgebase_version, "Version 2 All")) {
    return(FlyPhone:::V2A)
  } else {
    stop("Not a valid knowledgebase version! Options include: \"Version 1\",\"Version 2 All\", \"Version 2 High\", or \"Version 2 High/Moderate\".")
  }
}

# Gets the appropriate pathway core component information file based on the knowledgebase version chosen
getPathwayFile <- function(knowledgebase_version) {
  if(identical(knowledgebase_version, "Version 1")) {
    #return("./annotation/Pathway_core_components_2021vs1_clean.txt")
    return(FlyPhone:::pathway_components_v1)
  } else {
    #return("./annotation/Pathway_core_components_Version2-3_final.txt")
    return(FlyPhone:::pathway_components_v2)
  }
}

# load .rda object into a new variable #FIXME: Could be deleted
load_object <- function(file) {
  tmp <- new.env()
  load(file = file, envir = tmp)
  tmp[[ls(tmp)[1]]]
}
