#' Run FlyPhone pipeline
#'
#' Wrapper function for the FlyPhone pipeline.
#'
#' @param counts_fn The filepath to the counts matrix.
#' @param metadata_fn The filepath to the accompanying metadata file.
#' @param DEG The filepath to the DEG file, if provided.
#' @param pct_filter Percent threshold to filter expression of genes by. Default value of 0.1.
#' @param knowledgebase_version Version of knowledgebase to use. Valid values are: "Version 1", "Version 2 All", "Version 2 High", and "Version 2 High/Moderate".
#' @param perm_times The number of times to shuffle cluster alignments and calculate ligand/receptor averages for p-value calculation in raw interaction scoring. Default value of 1000.
#' @param delimitor The separator for the counts file if it is a .txt file. Default is tab.
#' @param control_name The name of the control sample, if applicable.
#' @param mutant_name The name of the mutant sample, if applicable.
#' @param deletePE Whether or not to delete the percentage expression file after the pipeline is finished. Defaults to true.
#'
#' @return NULL
#'
#' @export
RunFlyPhone <- function(counts_fn = NULL, metadata_fn = NULL, DEG = NULL, pct_filter = 0.1, knowledgebase_version, perm_times = 1000, delimitor = "\t", seuratObject = NULL, control_name = NULL, mutant_name = NULL, deletePE = TRUE) {
  # Preprocessing --------------------------------------------------------------

  # Boolean for checking if a DEG file is provided
  DEG_exists <- !is.null(DEG) && file.exists(DEG)

  # Load in annotation and pathway core component data depending on the knowledgebase version chosen
  annotationObj <- getAnnotationFile(knowledgebase_version)
  pathwayObj <- getPathwayFile(knowledgebase_version)

  # Initial subfolder creation
  dir.create("output")
  dir.create(".temp")

  # Pipeline -------------------------------------------------------------------

  # Calculate the raw interaction scores
  results <- CalculateInteractions(counts_fn, metadata_fn, annotationObj, pathwayObj, perm_times, knowledgebase_version, delimitor, seuratObject)

  # Read in sample names generated by CalculateInteractions()
  sampleNames <- gsub('^"|"$', '', readLines("sample_names.txt"))

  # Boolean for if multiple samples were detected
  isMultiSample <- length(results) > 1

  # Create the rest of the subfolders
  if(isMultiSample & DEG_exists) {
    dir.create("output/comparison")
    dir.create("output/comparison/chord-diagrams")
    dir.create("output/comparison/circleplots")

    for(name in sampleNames) {
      dir.create(paste0("output/", name, "/pathway-visualizations"))
    }

  } else {
    for(name in sampleNames) {
      dir.create(paste0("output/", name, "/heatmaps"))
      dir.create(paste0("output/", name, "/dotplots"))
      dir.create(paste0("output/", name, "/chord-diagrams"))
      dir.create(paste0("output/", name, "/circleplots"))
      dir.create(paste0("output/", name, "/pathway-visualizations"))
    }
  }

  # Only perform multi-sample analysis if a DEG file is provided
  if(isMultiSample & DEG_exists) {
    list_test <- AnalyzeMultiple(results, DEG, pct_filter, control_name, mutant_name) #FIXME: Might not actually use this variable at all
  } else {
    # Single-sample analysis OR Multi-sample analysis WITHOUT a DEG file provided
    AnalyzeSingle(results, pct_filter, knowledgebase_version)
  }

  doMultivis <- isMultiSample && DEG_exists

  # Generate cell-cell communication visualizations
  GenerateVisualizations(counts_fn, metadata_fn, doMultivis, pathwayObj, delimitor, seuratObject)

  # Generate pathway summary visualizations
  PathwayELVisualizations()

  # Remove the percentage expression file from the final output
  if(deletePE) {
    file.remove(".temp/Percentage_Expression.csv")
  }

  # Create a textfile specifying the type of analysis done
  if(isMultiSample & DEG_exists) {
    write.table("Multi_DEG", "output_type.txt", row.names = FALSE, col.names = FALSE)
  } else if (isMultiSample & !DEG_exists) {
    write.table("Multi", "output_type.txt", row.names = FALSE, col.names = FALSE)
  } else {
    write.table("Single", "output_type.txt", row.names = FALSE, col.names = FALSE)
  }
}

# Helper Functions -------------------------------------------------------------

# Gets the appropriate ligand/receptor pair dataset based on the knowledgebase version chosen
getAnnotationFile <- function(knowledgebase_version) {
  if(identical(knowledgebase_version, "Version 1")) {
    return(FlyPhone:::V1)
  } else if(identical(knowledgebase_version, "Version 2 High")) {
    return(FlyPhone:::V2H)
  } else if(identical(knowledgebase_version, "Version 2 High/Moderate")) {
    return(FlyPhone:::V2HM)
  } else if(identical(knowledgebase_version, "Version 2 All")) {
    return(FlyPhone:::V2A)
  } else {
    stop("Not a valid knowledgebase version! Options include: \"Version 1\",\"Version 2 All\", \"Version 2 High\", or \"Version 2 High/Moderate\".")
  }
}

# Gets the appropriate pathway core component information file based on the knowledgebase version chosen
getPathwayFile <- function(knowledgebase_version) {
  if(identical(knowledgebase_version, "Version 1")) {
    #return("./annotation/Pathway_core_components_2021vs1_clean.txt")
    return(FlyPhone:::pathway_components_v1)
  } else {
    #return("./annotation/Pathway_core_components_Version2-3_final.txt")
    return(FlyPhone:::pathway_components_v2)
  }
}

# load .rda object into a new variable #FIXME: Could be deleted
load_object <- function(file) {
  tmp <- new.env()
  load(file = file, envir = tmp)
  tmp[[ls(tmp)[1]]]
}
